name: MacDance
options:
  bundleIdPrefix: com.macdance
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.macdance.app
    SWIFT_VERSION: 6.0
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic

targets:
  MacDance:
    type: application
    platform: macOS
    sources:
      - path: MacDance
        excludes:
          - "Resources/**"
    resources:
      - path: MacDance/Resources
    settings:
      base:
        INFOPLIST_FILE: MacDance/Info.plist
        PRODUCT_NAME: MacDance
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    entitlements:
      path: MacDance/MacDance.entitlements
      properties:
        com.apple.security.device.camera: true
        com.apple.security.device.microphone: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true

  MacDanceTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MacDancetests
    dependencies:
      - target: MacDance
    settings:
      base:
        INFOPLIST_FILE: MacDancetests/Info.plist
